pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare https://SasikumarAnandhan@bitbucket.org/sasi-kumar/digital.git
          - cd digital.git
          - git push --mirror https://SasikumarAnandhan@github.com/SasikumarAnandhan/digital.git